Format and test Machines API docs
superfly/docs pull request #1369
Opened 2024-02-22 04:05 UTC by andie787

### Summary of changes

### Related Fly.io community and GitHub links

### Notes

2024-02-22 19:32 UTC, catflydotio requested changes

2024-02-22 19:32 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +    <%= render(CodeToggleComponent.new(badge: 'GET', title: '/apps/{app\_name}/machines/{machines\_id}/wait')) do |component| %>
```suggestion
    <%= render(CodeToggleComponent.new(badge: 'GET', title: '/apps/{app\_name}/machines/{machine\_id}/wait')) do |component| %>
```

2024-02-22 19:32 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +    <%= render(CodeToggleComponent.new(badge: 'POST', title: '/apps/{app\_name}/machines/{machines\_id}/lease')) do |component| %>
```suggestion
    <%= render(CodeToggleComponent.new(badge: 'POST', title: '/apps/{app\_name}/machines/{machine\_id}/lease')) do |component| %>
```

2024-02-22 19:32 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +    <%= render(CodeToggleComponent.new(badge: 'GET', title: '/apps/{app\_name}/machines/{machines\_id}/lease')) do |component| %>
```suggestion
    <%= render(CodeToggleComponent.new(badge: 'GET', title: '/apps/{app\_name}/machines/{machine\_id}/lease')) do |component| %>
```

2024-02-22 19:32 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +    <%= render(CodeToggleComponent.new(badge: 'DELETE', title: '/apps/{app\_name}/machines/{machines\_id}/lease')) do |component| %>
```suggestion
    <%= render(CodeToggleComponent.new(badge: 'DELETE', title: '/apps/{app\_name}/machines/{machine\_id}/lease')) do |component| %>
```

2024-02-23 00:59 UTC, andie787 commented on machines/api-machines-resource.html.markerb
> +    <%= render(CodeToggleComponent.new(badge: 'GET', title: '/apps/{app\_name}/machines/{machines\_id}/wait')) do |component| %>
fixed everywhere!

2024-02-23 18:39 UTC, catflydotio reviewed
After a skim of apps and volumes

2024-02-23 18:39 UTC, catflydotio commented on machines/api-volumes-resource.html.markerb
> +    <%= render(CodeSampleComponent.new(title: 'Status: 200 OK', language: 'json')) do %>
```suggestion
    <%= render(CodeSampleComponent.new(title: 'Status: 200 OK – Example response', language: 'json')) do %>
```

2024-02-23 18:39 UTC, catflydotio commented on machines/api-volumes-resource.html.markerb
> +    <%= render(CodeSampleComponent.new(title: 'Status: 200 OK', language: 'json')) do %>
```suggestion
    <%= render(CodeSampleComponent.new(title: 'Status: 200 OK – Example response', language: 'json')) do %>
```

2024-02-23 18:39 UTC, catflydotio commented on machines/api-apps-resource.html.markerb
> +      heading: 'Path parameters',
```suggestion
      heading: 'Query parameters',
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to get.'
```suggestion
      description: 'The ID of the Machine to stop.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to get.'
```suggestion
      description: 'The ID of the Machine to start.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to wait for.'
```suggestion
      description: 'The ID of the Machine to delete.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to wait for.'
```suggestion
      description: 'The ID of the Machine to create a lease for.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to wait for.'
```suggestion
      description: 'The ID of the Machine to retrieve any existing lease for.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to wait for.'
```suggestion
      description: 'The ID of the Machine to release any existing lease for.'
```

2024-02-23 19:08 UTC, catflydotio commented on machines/api-machines-resource.html.markerb
> +      description: 'The ID of the Machine to get.'
```suggestion
      description: 'The ID of the Machine to cordon or uncordon.'
```

2024-02-23 20:11 UTC, merged