Initial page for setting Vite Secrets for Laravel apps
superfly/docs pull request #1521
Opened 2024-05-12 19:18 UTC by KTanAug21

### Summary of changes
Create a page in the Laravel section of Fly.io docs to include a page that explains the steps needed in setting Vite environment variable!

### Preview
-none please

### Related Fly.io community and GitHub links
https://community.fly.io/t/how-to-setup-websocket-with-pusher-and-laravel-echo-on-deployment/19767

### Notes
.env files are not included during deployment of Laravel apps in Fly.io. But since Vite reads environment variables from .env files, we need to create a temporary .env.production file in the Dockerfile's asset bundling stage using build secrets during running of `fly deploy`.  This way, an appropriate .env file is present before building the assets and allow reading of the env variables.

This answers the issue raised by a [community member here!](https://community.fly.io/t/how-to-setup-websocket-with-pusher-and-laravel-echo-on-deployment/19767)

2024-06-18 12:11 UTC, hmshwt requested changes
Your instead of You're

2024-09-08 11:33 UTC, KTanAug21 commented
ALSO! This is a missing part of the docs above!

Since we need this `.env.production` file during build time, make sure that it's not excluded during build. Revise `.dockerignore` to remove that specific file exclusion:

```difference
/* .dockerignore */

// Please still exclude other .env files
.env
.env.backup

// We just need to remove the .env.production from exclusion
- .env.production
```

2026-07-02 18:29 UTC, kcmartin commented
Thanks for this, and apologies that it sat so long! Doing some PR triage and this one still fills a real gap (Vite env vars are a recurring community question), so we're not closing it. Before it can merge it needs the `.dockerignore` step from your follow-up comment folded in, the typo fix from review, and we'd want to drop `VITE_PUSHER_APP_SECRET` from the examples since VITE_-prefixed vars get bundled into public client JS. We'll follow up once we've decided whether to update this branch or rework the page.

2026-09-22 16:31 UTC, kcmartin commented
I'm closing this due to the Mintlify migration. Please open a new PR and retarget after cutover.

2026-09-22 16:31 UTC, closed without merging