Arcjet extension docs
superfly/docs pull request #1582
Opened 2024-06-17 12:39 UTC by davidmytton

### Summary of changes

Adds the [Arcjet](https://arcjet.com/) extension documentation.

### Notes

cc @jsierles

2024-06-17 18:20 UTC, jsierles requested changes

2024-06-17 18:20 UTC, jsierles commented on reference/arcjet.html.md
> +Then set the `ARCJET_KEY` secret on your app.
If you run the command in your app directory, the key will be set automatically. If you set it outside the app directory, you'd need to manually run this command.

2024-06-17 19:10 UTC, jsierles approved these changes
Generally looks good. It would be good to add a section about pricing, even if it isn't worked out yet, and also a callout about being in beta, and what that means. Check the Supabase docs for details on that: https://fly.io/docs/reference/supabase/

2024-06-18 10:23 UTC, jsierles approved these changes

2024-06-19 09:33 UTC, davidmytton commented
@jsierles looks like the Vale linter needs updating to allow lower-case `arcjet` in the URLs.

2024-06-19 09:59 UTC, jsierles commented
You can add here https://github.com/superfly/docs/blob/main/styles/config/vocabularies/fly-terms/accept.txt

2024-06-19 21:08 UTC, merged