added documentation for force ssl configuration
superfly/docs pull request #85
Opened 2022-03-08 15:04 UTC by senyosimpson

Still need to proof-read and view locally

2022-03-08 15:32 UTC, jsierles requested changes
Thanks for taking care of this. I suggested some changes.

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +### Compress
Perhaps better to name this `Disable response compression`

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +### Compress
Also, provide example code like all the other options do.

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +### Response
Same here, maybe `Modifying Response Headers`. And below, "The `response` section allows you to add or remove HTTP headers to the response.

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +A header is removed by setting it to `false`
Perhaps `Remove a header by setting it 'false'`

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +> This option is only applicable to HTTP handlers. If you accidentally set it on an HTTPS handler, nothing will happen
Missing . here.

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +which will return a response like so
Maybe better not to split up sentences like this. Make a full sentence here like `This configuration responds with:`

2022-03-08 15:32 UTC, jsierles commented on reference/configuration.html.md
> +* `http_options` : A table that specifies configuration options for HTTP handlers. It is entirely optional and can be left out.
Maybe just say `An optional table to specify configuration` and cull the second sentence.

2022-03-08 15:32 UTC, jsierles commented on reference/services.html.md.erb
> +`http_options` is used to specify additional configuration for HTTP handlers.
Maybe activate with "Use `http_options` to specify..."

2022-03-15 10:44 UTC, senyosimpson commented on reference/services.html.md.erb
> +At present, there is no support for redirecting to a TLS handler on a port other than 443, using a different status code or redirecting specific requests.
@jsierles Should this be included? I'm not sure how we communicate these type of limitations

2022-03-15 10:50 UTC, senyosimpson commented
@jsierles I think we should hold off merging this in for a bit of time. At least, let me get it out on the community forum first and then we can put this in

2022-03-22 13:33 UTC, senyosimpson commented
The HTTPS redirects feature was moved out of the HTTP options. I'd rather not bundle all the changes together (and I'm not sure we want the HTTP options in the official documentation as of yet)

2022-03-22 13:33 UTC, closed without merging