Add hint about specifying dockerfile in case it is not automatically …
superfly/docs pull request #899
Opened 2023-07-23 21:27 UTC by tomczakdominik

…detected

I have a Rails app which has a dockerfile named `Dockerfile` in a main directory and still `fly launch` was trying to build it as a ruby app, hence I'm adding this hint.

2023-07-23 23:39 UTC, rubys requested changes

2023-07-23 23:39 UTC, rubys commented on languages-and-frameworks/dockerfile.html.md.erb
> +Let `fly launch` generate an app name for you or pick your own. You may need to explicitily specify Dockerfile path using `--dockerile` flag if fly doesn't detect Dockerfile automatically.
There are two typos in that one sentence.

2023-07-23 23:39 UTC, rubys commented on languages-and-frameworks/dockerfile.html.md.erb
> +Let `fly launch` generate an app name for you or pick your own. You may need to explicitily specify Dockerfile path using `--dockerile` flag if fly doesn't detect Dockerfile automatically.
The issue isn't that fly doesn't detect the Dockerfile automatically, successfully launching a Rails application typically requires the setting of at least one secret (RAILS_MASTER_KEY), and either the deployment of a database or the creation of a volume.  That's why the scanner for Rails is run before the Dockerfile scanner.

2026-07-01 20:15 UTC, kcmartin commented
Thanks for the suggestion, and sorry for the long delay! This page has since been rewritten, and the `--dockerfile` flag is now covered in the flyctl command reference. Closing this out, but thanks for flagging it.

2026-07-01 20:15 UTC, closed without merging